### ISSUE TITLE
Add Sunspot.index! in documentation

### ISSUE THREAD

**Issue by martinszy** [ciudadanointeligente/bill-it#54]
The best method for reindexing is using Sunspot.index! Bills.all (or another query) in the rails console. Please add that to the docs.

**Comment by martinszy** [comment]
Done, I did it myself.

**Comment by martinszy** [comment]
This is not working properly. The documentation needs to say how to create that Bills constant.

t$ bundle exec rails console
Loading development environment (Rails 3.2.13)
2.0.0 :001 > Sunspot.index! Bills.all 
NameError: uninitialized constant Bills
        from (irb):1
        from /home/billit/bill-it/vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
        from /home/billit/bill-it/vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in`start'
        from /home/billit/bill-it/vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
        from script/rails:6:in`require'
        from script/rails:6:in `<main>'

**Comment by martinszy** [comment]
What is missing is to run bundle exec with the ENV varialbe set.
ENV=production bundle exec rails console
