### ISSUE TITLE
Sometimes billit stops responding

### ISSUE THREAD

**Issue by martinszy** [ciudadanointeligente/bill-it#62]
When I'm running a batch import process, I regularly get timeout errors. I think that billit keeps consuming more and more resources until the server can't handle it and it slows down until the client times out. After the client has failed, I can resume the process without problems until the next timeout. The approximate amount of requests I can perform before it dies is 4000.

/usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
        from /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/protocol.rb:152:in`rbuf_fill'
        from /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
        from /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/protocol.rb:144:in`readline'
        from /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
        from /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/http/response.rb:28:in`read_new'
        from /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/http.rb:1406:in `block in transport_request'
        from /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/http.rb:1403:in`catch'
        from /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
        from /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/http.rb:1376:in`request'
        from /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/http.rb:1369:in `block in request'
        from /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/http.rb:852:in`start'
        from /usr/local/rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/net/http.rb:1367:in `request'
        from /usr/local/rvm/gems/ruby-2.0.0-p451/gems/roar-0.11.19/lib/roar/representer/transport/net_http.rb:40:in`do_request'
        from /usr/local/rvm/gems/ruby-2.0.0-p451/gems/roar-0.11.19/lib/roar/representer/transport/net_http.rb:16:in `post_uri'
        from /usr/local/rvm/gems/ruby-2.0.0-p451/gems/roar-0.11.19/lib/roar/representer/feature/http_verbs.rb:35:in`post'
        from bills-to-billit.rb:86:in `post'
        from bills-to-billit.rb:123:in`block in <main>'
        from bills-to-billit.rb:105:in `select'
        from bills-to-billit.rb:105:in`<main>'

**Comment by martinszy** [comment]
I guess the problem is that attachments take a long time to create, so I removed the attachments from the project. The attachment means that it goes to the server to fecth the full text of the bill instead of just storing the URL.
